### ISSUE TITLE
Nativescript 3.4.0 Webpack giving a  'Cannot read property 'init' of undefined' error.

### ISSUE THREAD

**Issue by skhye05** [EddyVerbruggen/nativescript-secure-storage#13]
I am trying the plugin on nativescript 3.4.0 angular and when i am using webpack i am getting the following error:

`JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'init' of undefined
JS: TypeError: Cannot read property 'init' of undefined`

which is related to this portion of the plugin code:
`    function SecureStorage() {
    this.hawk = com.orhanobut.hawk.Hawk.init(utils.ad.getApplicationContext()).build();
}`

What could be the issue here?

**Comment by DODODODOit** [comment]
I have same issue on nativescript 3.4.0 and 3.4.1
first >
$ tns info
nativescript / 3.4.1 / 3.4.1 / up to date
tns-core-modules / 3.4.0 / 3.4.0 / up to date
tns-android / 3.4.1 / 3.4.1 / up to date 

second>
$ tns update next
nativescript / 3.4.1 / 3.4.1 / up to date
tns-core-modules / 4.0.0-2018-01-08-02 / 3.4.0 / up to date
tns-android / 3.4.1-2018-01-12-01 / 3.4.1 / update available

And then, the issue was solved.
... I don't know how can this soled the issue.
but It was good solution to me. I hope this solution will be helpful to you.
Thank you for reading this post that written by my unskilled English.
ps. I hope somebody will post about how could this solution have made problem solved.

**Comment by jomis** [comment]
Same problem for me with the following versions.

│ nativescript     │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date  │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │

It works fine on iOS but exits with the above error on Android. The upgrade to **next** solution is not an option since this usually is not recommend for production releases.

**Comment by gummibjorn** [comment]
i think in the nativescript/android-runtime version 3.4.0 exists a bug regarding plugin dependencies. I assume this error is caused by a missing package (com.orhanobut.hawk) which is a secure-storage implementation for android.

the bug mentioned is fixed in android-runtime version 3.4.1

see PR [#918](https://github.com/NativeScript/android-runtime/pull/918)

**Comment by jacopo69** [comment]
I had the same problem.
After uninstalling the app on device, removing the platform (_tns platform remove android_) and readding the platform (_tns platform add android_) I solved.

**Comment by beawolf** [comment]
Confirming @jacopo69, a `tns platform remove android` and `tns platform add android` command chain is definitely required when you first add _nativescript-secure-storage_ plugin to your NativeScript project.

**Comment by EddyVerbruggen** [comment]
That's true for all plugins wrapping native libraries.

**Comment by aaayushsingh** [comment]
I am still facing this issue. The above steps didn't work for me.
